# Site settings
title: Lake Park Podiatry
email: hkstarkdpm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

phone: +1(561)848-7799
address:
  name: Lake Park Podiatry
  street: 701 Park Avenue
  city: Lake Park
  state: FL
  zip: 33401

# Build settings
markdown: kramdown
